[package]
name = "render-example"
version = "0.1.0"
edition = "2024"

[dependencies]
ecs = { path = "../../crates/ecs" }
render = { path = "../../crates/render" }
window = { path = "../../crates/window" }
