[package]
name = "assets"
version = "0.1.0"
edition = "2024"

[dependencies]
ecs = { path = "../ecs" }
uuid = { workspace = true }
serde = { workspace = true, features = ["derive"] }
ron = { workspace = true }
