[package]
name = "input"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-input = { path = "../macros/derive-input" }
ecs = { path = "../ecs" }
math = { path = "../math" }
smol_str = "0.2.0"
