[package]
name = "derive-render"
version = "0.1.0"
edition = "2024"

[lib]
name = "derive_render"
proc-macro = true

[dependencies]
encase_derive_impl = "0.11.0"
macro-utils = { path = "../utils" }
bitflags = { workspace = true }
