[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
asset = { path = "../asset" }
ecs = { path = "../ecs" }
math = { path = "../math" }
renderer = { path = "../renderer" }
slotmap = { workspace = true }
bitflags = { workspace = true }
smallvec = { workspace = true }
fontdue = "0.9.3"
